Lesson 1
fekisa/GeekBrains pull request #1
Opened 2020-01-21 17:01 UTC by fekisa

Первое домашнее задание

2020-01-22 22:16 UTC, GefMar commented on .idea/workspace.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Этот файл желательно добавить в .gitignore

2020-01-22 22:16 UTC, GefMar commented on homework_1_2.py
> +hour = ((input_second // 3600)) % 24
зачем двойные скобки?

2020-01-23 03:49 UTC, fekisa commented on .idea/workspace.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Вроде добавила, но не уверена =)

2020-01-23 03:50 UTC, fekisa commented on homework_1_2.py
> +hour = ((input_second // 3600)) % 24
убрала двойные скобки в 7 строке
в 5 не стала, т.к. одна идет на int, вторая на input

2020-01-23 16:20 UTC, fekisa commented
Взяла с гита шаблонный файл на pycharm и добавила DS_Store. Нужно мержить?

2020-01-23 16:58 UTC, vzuev401 commented
Так, ну игнор работает на *untracked* файлах. Сейчас добавленные в игнор файлы у вас всё ещё видны в репозитории, а значит, что они у вас отслеживаются.

[Untracked basically means that Git sees a file you didn't have in the previous snapshot (commit)](https://git-scm.com/book/en/v2/Git-Basics-Recording-Changes-to-the-Repository)

Вам нужно создать коммит, в котором их не будет, для этого `git rm -r --cached .idea/ **/.DS_Store`. Ну а дальше изменения поместить в индекс и сделать снимок.

2020-01-23 17:00 UTC, vzuev401 requested changes

2020-01-23 17:00 UTC, vzuev401 commented on .gitignore
> +*.DS_Store
Лучше добавить игнор на все подобные файлы внутри рабочей области.

`**/.DS_Store`

__**__ означает любую глубину, __*__ работает несколько иначе

2020-01-24 17:33 UTC, closed without merging